version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    ports:
      - 8080:8080
    command: npm run dev